# Generated by Django 5.2.3 on 2025-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
